# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 04:28
from __future__ import unicode_literals

import books.storage
import books.uuidfield
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_file', models.FileField(storage=books.storage.LinkOrFileSystemStorage(), upload_to=b'books')),
                ('original_path', models.CharField(max_length=1016, verbose_name=b'file')),
                ('file_sha256sum', models.CharField(max_length=64, unique=True)),
                ('mimetype', models.CharField(max_length=200, null=True)),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to=b'covers')),
                ('a_id', books.uuidfield.UUIDField(blank=True, editable=False, max_length=36, verbose_name=b'atom:id')),
                ('a_title', models.CharField(max_length=200, verbose_name=b'atom:title')),
                ('a_author', models.CharField(max_length=200, verbose_name=b'atom:author')),
                ('a_updated', models.DateTimeField(auto_now=True, verbose_name=b'atom:updated')),
                ('a_summary', models.TextField(blank=True, null=True, verbose_name=b'atom:summary')),
                ('a_category', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'atom:category')),
                ('a_rights', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'atom:rights')),
                ('dc_publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'dc:publisher')),
                ('dc_issued', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'dc:issued')),
                ('dc_identifier', models.CharField(blank=True, help_text=b'Use ISBN for this', max_length=50, null=True, verbose_name=b'dc:identifier')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('downloads', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-time_added',),
                'get_latest_by': 'time_added',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name=b'language name')),
                ('code', models.CharField(blank=True, max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tag group',
                'verbose_name_plural': 'Tag groups',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='a_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Status'),
        ),
        migrations.AddField(
            model_name='book',
            name='dc_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
